### ISSUE TITLE
compose RbacDefinition change

### ISSUE THREAD

**Issue by talsharon48** [dana-team/permission-granter-controller#15]
currently the compose rbac definition function is an example only, needs to be changed to real functionality:

cluster-admin on label selector namespaces
OCP list of white list cluster-wide permissions

**Comment by mzeevi** [comment]
The ClutserRole is as follows:

/assign @liadlauber 

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rks-user-permission
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - update
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - persistentvolumes
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - authorization.openshift.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - config.openshift.io
    resources:
      - images
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - list
      - get
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
      - clusterversions
      - consoles
      - dnses
      - featuregates
      - infrastructures
      - ingresses
      - networks
      - oauths
      - operatorhubs
      - projects
      - proxies
      - schedulers
  - verbs:
      - list
      - get
    apiGroups:
      - console.openshift.io
    resources:
      - consoleclidownloads
      - consoleexternalloglinks
      - consolelinks
      - consolenotifications
      - consoleyamlsamples
  - verbs:
      - list
      - get
    apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - flowschemas
      - prioritylevelconfigurations
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups: 
      - helm.openshift.io
    resources:
      - helmchartrepositories
  - verbs:
      - list
      - get
    apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - config
      - imagepruners
  - verbs:
      - list
      - get
    apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - containerruntimeconfigs
      - controllerconfigs
      - kubeletconfigs
      - machineconfigpools
      - machineconfigs
  - verbs:
      - list
      - get
    apiGroups:
      - metal3.io
    resources:
      - provisionings
  - verbs:
      - list
      - get
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
  - verbs:
      - list
      - get
    apiGroups:
      - migration.k8s.io
    resources:
      - storagestates
      - storageversionmigrations
  - verbs:
      - list
      - get
    apiGroups:
      - image.openshift.io
    resources:
      - images
      - imagesignatures
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
  - verbs:
      - list
      - get
    apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
  - verbs:
      - list
      - get
    apiGroups:
      - operator.openshift.io
    resources:
      - authentications
      - cloudcredentials
      - clustercsidrivers
      - configs
      - consoles
      - csisnapshotcontrollers
      - dnses
      - etcds
      - imagecontentsourcepolicies
      - kubeapiservers
      - kubecontrollermanagers
      - kubeschedulers
      - kubestorageversionmigrators
      - networks
      - openshiftapiservers
      - openshiftcontrollermanagers
      - servicecas
      - storages
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - list
      - get
    apiGroups:
      - samples.operator.openshift.io
    resources:
      - configs
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
  - verbs:
      - list
      - get
      - update
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
  - verbs:
      - list
      - get
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
      - volumesnapshotcontents
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
  - verbs:
      - list
      - get
    apiGroups:
      - template.openshift.io
    resources:
      - brokertemplateinstances
  - verbs:
      - create
      - list
      - get
      - update
      - delete
    apiGroups:
      - user.openshift.io
    resources:
      - groups
      - identities
      - useridentitymappings
      - users
```

**Comment by mzeevi** [comment]
Made some changes to the Role to add some things:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rks-user-permission
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - componentstatuses
  - verbs:
      - create
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumes
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - resourceaccessreviews
      - subjectaccessreviews
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - authorization.openshift.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - builds
      - images
      - ingresses
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
      - clusterversions
      - consoles
      - dnses
      - featuregates
      - infrastructures
      - ingresses
      - networks
      - oauths
      - operatorhubs
      - projects
      - proxies
      - schedulers
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consoleclidownloads
      - consoleexternalloglinks
      - consolelinks
      - consolenotifications
      - consoleyamlsamples
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - flowschemas
      - prioritylevelconfigurations
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups: 
      - helm.openshift.io
    resources:
      - helmchartrepositories
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - config
      - imagepruners
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - containerruntimeconfigs
      - controllerconfigs
      - kubeletconfigs
      - machineconfigpools
      - machineconfigs
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - metal3.io
    resources:
      - provisionings
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - migration.k8s.io
    resources:
      - storagestates
      - storageversionmigrations
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - image.openshift.io
    resources:
      - images
  - verbs:
      - create
      - delete
    apiGroups:
      - image.openshift.io
    resources:
      - imagesignatures
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - oauth.openshift.io
    resources:
      - oauthaccesstokens
      - oauthauthorizetokens
      - oauthclientauthorizations
      - oauthclients
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - operator.openshift.io
    resources:
      - authentications
      - cloudcredentials
      - clustercsidrivers
      - configs
      - consoles
      - csisnapshotcontrollers
      - dnses
      - etcds
      - imagecontentsourcepolicies
      - kubeapiservers
      - kubecontrollermanagers
      - kubeschedulers
      - kubestorageversionmigrators
      - networks
      - openshiftapiservers
      - openshiftcontrollermanagers
      - servicecas
      - storages
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - policy
    resources:
      - podsecuritypolicies
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - samples.operator.openshift.io
    resources:
      - configs
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - rangeallocations
      - securitycontextconstraints
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - security.internal.openshift.io
    resources:
      - rangeallocations
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
      - volumesnapshotcontents
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - template.openshift.io
    resources:
      - brokertemplateinstances
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - user.openshift.io
    resources:
      - groups
      - identities
      - users
  - verbs:
      - create
      - delete
      - get
      - patch
      - update
```

**Comment by mzeevi** [comment]
After trying to deploy `ArgoCD` with this set of permissions, we saw that we have to give [Escalate verb](https://kubernetes.io/docs/concepts/security/rbac-good-practices/#escalate-verb), which means the user would be able to give itself `ClusterAdmin` permissions anyway.

So what we're gonna do is use the role for all users and allow them to give themselves `ClusterAdmin` if needed. That would mitigate the problem, but we're still allowing.

**Comment by mzeevi** [comment]
Modified `ClusterRole`:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rks-user-permission
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - componentstatuses
  - verbs:
      - create
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - persistentvolumes
  - verbs:
      - '*'
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - '*'
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
  - verbs:
      - '*'
    apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
  - verbs:
      - create
    apiGroups:
      - authentication.k8s.io
    resources:
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - resourceaccessreviews
      - subjectaccessreviews
  - verbs:
      - '*'
    apiGroups:
      - authorization.openshift.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - '*'
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - '*'
    apiGroups:
      - config.openshift.io
    resources:
      - builds
      - images
      - ingresses
  - verbs:
      - '*'
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - config.openshift.io
    resources:
      - clusteroperators
      - clusterversions
      - consoles
      - dnses
      - featuregates
      - infrastructures
      - ingresses
      - networks
      - oauths
      - operatorhubs
      - projects
      - proxies
      - schedulers
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - console.openshift.io
    resources:
      - consoleclidownloads
      - consoleexternalloglinks
      - consolelinks
      - consolenotifications
      - consoleyamlsamples
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - flowschemas
      - prioritylevelconfigurations
  - verbs:
      - '*'
    apiGroups: 
      - helm.openshift.io
    resources:
      - helmchartrepositories
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - config
      - imagepruners
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - containerruntimeconfigs
      - controllerconfigs
      - kubeletconfigs
      - machineconfigpools
      - machineconfigs
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - metal3.io
    resources:
      - provisionings
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
  - verbs:
      - '*'
    apiGroups:
      - migration.k8s.io
    resources:
      - storagestates
      - storageversionmigrations
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - image.openshift.io
    resources:
      - images
  - verbs:
      - create
      - delete
    apiGroups:
      - image.openshift.io
    resources:
      - imagesignatures
  - verbs:
      - '*'
    apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - node.k8s.io
    resources:
      - runtimeclasses
  - verbs:
      - '*'
    apiGroups:
      - oauth.openshift.io
    resources:
      - oauthaccesstokens
      - oauthauthorizetokens
      - oauthclientauthorizations
      - oauthclients
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - operator.openshift.io
    resources:
      - authentications
      - cloudcredentials
      - clustercsidrivers
      - configs
      - consoles
      - csisnapshotcontrollers
      - dnses
      - etcds
      - imagecontentsourcepolicies
      - kubeapiservers
      - kubecontrollermanagers
      - kubeschedulers
      - kubestorageversionmigrators
      - networks
      - openshiftapiservers
      - openshiftcontrollermanagers
      - servicecas
      - storages
  - verbs:
      - '*'
    apiGroups:
      - policy
    resources:
      - podsecuritypolicies
  - verbs:
      - '*'
    apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - samples.operator.openshift.io
    resources:
      - configs
  - verbs:
      - '*'
    apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
  - verbs:
      - '*'
    apiGroups:
      - security.openshift.io
    resources:
      - rangeallocations
      - securitycontextconstraints
  - verbs:
      - '*'
    apiGroups:
      - security.internal.openshift.io
    resources:
      - rangeallocations
  - verbs:
      - '*'
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
      - volumesnapshotcontents
  - verbs:
      - '*'
    apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - template.openshift.io
    resources:
      - brokertemplateinstances
  - verbs:
      - '*'
    apiGroups:
      - user.openshift.io
    resources:
      - groups
      - identities
      - users
  - verbs:
      - '*'
```
